[workspace]
members = ["verify/aizu-online-judge", "verify/library-checker"]

[package]
name = "procon-lib-rs"
version = "0.1.7"
authors = ["stuart0035"]
edition = "2021"
license = "CC0-1.0"

[lib]
name = "procon_lib"

[dependencies]

[dev-dependencies]
static_assertions = "1.1.0"
